SOA AM - kolokwium 2/SOA/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
namespace Web.Controllers
{
    public class BaseController:Controller
    {
        protected readonly IMapper _mapper;
        public BaseController(IMapper mapper)
        {
            _mapper = mapper;
        }
    }
}

SOA AM - kolokwium 2/SOA/Controllers/GraController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;
using ViewModels.ViewModels;
using Model.DataModels;
namespace Web.Controllers
{
    public class GraController : BaseController
    {
        private readonly IGra _gra;
        public GraController(IMapper mapper, IGra gra) : base(mapper)
        {
            _gra = gra;
        }
        
        public IActionResult Index()
        {
            var wynik = _gra.GetGry();
            return View(wynik);
        }
        public IActionResult AddVm()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddVm(GraVm graVm)
        {
            var gra = _mapper.Map<Gra>(graVm);
            _gra.AddVm(gra);
            return View();
        }
        [HttpPost]
        public IActionResult Index(GraVm graVm, int id)
        {
            _gra.Update(graVm, id);
            var wynik = _gra.GetGry();
            return View(wynik);
        }
        [HttpPost]
        public IActionResult Remove(int Id)
        {
            _gra.Remove(Id);
            var wynik = _gra.GetGry();
            Index();
            return View(wynik);
        }
        [HttpPost]
        public IActionResult Update(int Id)
        {
            var wynik = _gra.Get(Id);
            return View(wynik);
        }
    }
}

SOA AM - kolokwium 2/SOA/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace SOA.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SOA AM - kolokwium 2/SOA/Views/Gra/AddVm.cshtml
@model ViewModels.ViewModels.GraVm;

<form method="Post" asp-action="AddVm">
    <label asp-for="Tytul">Tytul</label>
    <input asp-for="Tytul">
    <label asp-for="RokWydania">Rok Wydania</label>
    <input asp-for="RokWydania">
    <label asp-for="Wydawnictwo">Wydawnictwo</label>
    <input asp-for="Wydawnictwo">
    <button type="submit">Dodaj</button>
</form>

SOA AM - kolokwium 2/SOA/Views/Gra/Index.cshtml
@model ICollection<ViewModels.ViewModels.GraVm>

    <table>
        <tr>
        <th>Id</th>
        <th>Tytul</th>
        <th>Rok Wydania</th>
        <th>Wydawca</th>
        </tr>
        @foreach (var gra in @Model){
            <tr>
                <th>@gra.Id</th>
             <th>@gra.Tytul</th>
                <th>@gra.RokWydania</th>
                <th>@gra.Wydawnictwo</th>
                <th> <a asp-controller="Gra" asp-action="Remove" asp-route-Id=@gra.Id>Usun</a></th>
		        <th> <a asp-controller="Gra" asp-action="Update" asp-route-Id=@gra.Id>Update</a></th>

            </tr>
        }
    </table>

SOA AM - kolokwium 2/SOA/Views/Gra/Remove.cshtml
@model IList<ViewModels.ViewModels.GraVm>
<table>
	<tr>
		<th>Id</th>
		<th>Marka</th>
		<th>Model</th>
		<th>RokProdukcji</th>
		<th>Usun</th>
		<th>Update</th>
	</tr>
	@foreach (var sam in @Model)
	{
		<tr>
			<th>@sam.Id</th>
			<th>@sam.Tytul</th>
			<th>@sam.RokWydania</th>
			<th>@sam.Wydawnictwo</th>
			<th> <a asp-controller="Gra" asp-action="Remove" asp-route-Id=@sam.Id>Usun</a></th>
			<th> <a asp-controller="Gra" asp-action="Update" asp-route-Id=@sam.Id>Update</a></th>
		</tr>

	}
</table>

SOA AM - kolokwium 2/SOA/Views/Gra/Update.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

SOA AM - kolokwium 2/SOA/Views/Home/Index.cshtml
Hello!

SOA AM - kolokwium 2/SOA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/w3-css/w3.css" asp-append-version="true" />
</head>
<body>
    <div class="w3-content" style="max-width:1500px">
        <header class="w3-panel w3-center w3-opacity">
            <nav class="w3-bar w3-border">
                <a class="w3-bar-item w3-button" asp-controller="Home" asp-action="Index">Home</a>
                <a class="w3-bar-item w3-button" asp-controller="Author" asp-action="Index">Autorzy</a>
                <a class="w3-bar-item w3-button" asp-controller="Author" asp-action="AddOrUpdateAuthor" asp-route-id="0">Dodaj autora</a>
                <a class="w3-bar-item w3-button" asp-controller="Article" asp-action="Index">Artykuły</a>
            </nav>
        </header>
        <main>
            @RenderBody()
        </main>
    
        <footer class="w3-panel w3-center">
            &copy; 2022
        </footer>
    </div>
</body>
</html>